//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitorTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ServiceMonitor : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServiceMonitor defaultInstance = ((ServiceMonitor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServiceMonitor())));
        
        public static ServiceMonitor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProcessesToCheck {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProcessesToCheck"]));
            }
            set {
                this["ProcessesToCheck"] = value;
            }
        }
    }
}
